apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: vessel-vissionaries-deploy
  annotations:
    scenarios.ai.sap.com/description: "Vessel Vissionaries deploy scenario"
    scenarios.ai.sap.com/name: "vessel-vissionaries-deploy-scenario"
    executables.ai.sap.com/description: "Inference executable for image classification"
    executables.ai.sap.com/name: "vessel-vissionaries-deploy-exec"
  labels:
    scenarios.ai.sap.com/id: "vessel-vissionaries-deploy"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: 
       - name: modelName
         default: value
         type: string
         description: model name
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
        - name: case1
        minReplicas: 0
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: "docker.io/gdoraominsait/vessel-visionaries-detect:0.0.1"
          ports:
            - containerPort: 9001
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
