apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: case1-serving-pipeline
  annotations:
    scenarios.ai.sap.com/name: "Case1 Bottle Detection Scenario"
    scenarios.ai.sap.com/description: "Image detection with bottles of Estrella Galicia"

    executables.ai.sap.com/name: "case1-model-serving"
    executables.ai.sap.com/description: "Serving CV model with Estrella Galicia dataset"

  labels:
    scenarios.ai.sap.com/id: "case1-detection-scenario"
    ai.sap.com/version: "1.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: case1
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: docker.io/gdoraominsait/vessel_visionaries_serve:latest
          ports:
            - containerPort: 9001
              protocol: TCP
          command: ["/bin/sh", "-c", "python /app/src/main.py"]