services:
  app:
    container_name: vessel_visionaries_serve
    image: gdoraominsait/vessel_visionaries_serve:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "python /app/src/main.py"]
    volumes:
      - ../training/app/model:/mnt/models
      - ../training/app/runs:/runs
    ports:
      - "9001:9001"